import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { motion } from "framer-motion";
import { ArrowRight, Bot, Layers, Zap, BookOpen } from "lucide-react";
import { useArticles } from "@/hooks/use-articles";
import { ArticleCard } from "@/components/ArticleCard";

export default function Home() {
  const { data: articles, isLoading } = useArticles();

  return (
    <div className="flex flex-col min-h-screen">
      {/* Hero Section */}
      <section className="relative overflow-hidden pt-20 pb-32 lg:pt-32 lg:pb-48 bg-gradient-to-b from-orange-50/50 to-background dark:from-orange-950/10 dark:to-background">
        <div className="container px-4 md:px-6 mx-auto relative z-10">
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="flex flex-col items-center text-center max-w-4xl mx-auto space-y-8"
          >
            <div className="inline-flex items-center rounded-full border px-3 py-1 text-sm font-medium bg-background shadow-sm text-orange-600 border-orange-200">
              <span className="flex h-2 w-2 rounded-full bg-orange-600 mr-2 animate-pulse"></span>
              AI-Powered Project Management
            </div>
            
            <h1 className="text-4xl md:text-6xl lg:text-7xl font-bold font-display tracking-tight text-foreground">
              Master Your Projects with <br/>
              <span className="text-gradient">Intelligent Insights</span>
            </h1>
            
            <p className="text-lg md:text-xl text-muted-foreground max-w-2xl leading-relaxed">
              Access premium templates, AI-generated guides, and expert articles to elevate your project management career. Join the next generation of PMs.
            </p>
            
            <div className="flex flex-col sm:flex-row gap-4 w-full sm:w-auto">
              <Link href="/articles">
                <Button size="lg" className="w-full sm:w-auto text-lg h-12 px-8 bg-orange-500 hover:bg-orange-600 shadow-lg shadow-orange-500/25">
                  Explore Articles
                </Button>
              </Link>
              <Link href="/pricing">
                <Button variant="outline" size="lg" className="w-full sm:w-auto text-lg h-12 px-8">
                  View Premium Packs
                </Button>
              </Link>
            </div>
          </motion.div>
        </div>
        
        {/* Background decorative elements */}
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[800px] bg-orange-500/5 rounded-full blur-3xl -z-10" />
      </section>

      {/* Features Section */}
      <section className="py-20 bg-background">
        <div className="container px-4 mx-auto">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <FeatureCard 
              icon={<Bot className="w-8 h-8 text-orange-500" />}
              title="AI Generation"
              description="Articles and PDFs generated by advanced AI specifically for modern project management challenges."
            />
            <FeatureCard 
              icon={<Layers className="w-8 h-8 text-blue-500" />}
              title="Premium Templates"
              description="Download ready-to-use PDF templates and guides to streamline your workflow instantly."
            />
            <FeatureCard 
              icon={<Zap className="w-8 h-8 text-amber-500" />}
              title="Real-time Updates"
              description="Stay ahead of the curve with content that evolves as fast as the industry does."
            />
          </div>
        </div>
      </section>

      {/* Latest Articles */}
      <section className="py-20 bg-muted/30">
        <div className="container px-4 mx-auto">
          <div className="flex justify-between items-end mb-12">
            <div>
              <h2 className="text-3xl font-bold font-display mb-2">Latest Insights</h2>
              <p className="text-muted-foreground">Fresh perspectives on project management</p>
            </div>
            <Link href="/articles">
              <Button variant="ghost" className="group">
                View All <ArrowRight className="ml-2 w-4 h-4 group-hover:translate-x-1 transition-transform" />
              </Button>
            </Link>
          </div>

          {isLoading ? (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              {[1, 2, 3].map((i) => (
                <div key={i} className="h-96 bg-muted animate-pulse rounded-2xl" />
              ))}
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              {articles?.slice(0, 3).map((article) => (
                <ArticleCard key={article.id} article={article} />
              ))}
            </div>
          )}
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20">
        <div className="container px-4 mx-auto">
          <div className="bg-foreground rounded-3xl p-8 md:p-16 text-center text-background relative overflow-hidden">
            <div className="absolute top-0 right-0 p-32 bg-orange-500/20 rounded-full blur-3xl transform translate-x-1/2 -translate-y-1/2" />
            
            <div className="relative z-10 max-w-2xl mx-auto space-y-6">
              <h2 className="text-3xl md:text-4xl font-bold font-display text-white">
                Ready to level up your career?
              </h2>
              <p className="text-gray-400 text-lg">
                Get unlimited access to our entire library of premium resources and AI tools with our Lifetime Pack.
              </p>
              <Link href="/pricing">
                <Button size="lg" className="bg-orange-500 hover:bg-orange-600 text-white border-none shadow-xl shadow-orange-900/20">
                  Get Lifetime Access <Zap className="ml-2 w-4 h-4" />
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}

function FeatureCard({ icon, title, description }: { icon: React.ReactNode, title: string, description: string }) {
  return (
    <div className="p-6 rounded-2xl bg-card border hover:shadow-lg transition-shadow duration-300">
      <div className="mb-4 p-3 bg-muted w-fit rounded-xl">{icon}</div>
      <h3 className="text-xl font-bold mb-2 font-display">{title}</h3>
      <p className="text-muted-foreground leading-relaxed">{description}</p>
    </div>
  );
}
